language: php
sudo: false

php:
  - 7.0

branches:
  only:
  - master

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - wget http://codeception.com/codecept.phar

script:
  - make

notifications:
  slack:
    secure: KuS7FK9w7KHUN3JcwndkdMCTKrjGF0eY8RPi+9NLXOAnt+2q+CQ2iFxZabkl+3DOj1xtAfsrC/dVVq+gJv72/5y1tNbwNUOGHZYQHmUtkpTjEAAZJK7icUMRNFMiiYundAH+raMJ1q/D63pULo3z7r7a0yeJZi+YnCDBi2e9mIUPlwkIn3ibElFSkwS5xR6tvYTe1C5e+9gUT5sNIuxiVx/dqvxuRdWYm27lTNWVd6lFt2beEnrjiSGCpa/JzxKhd3QwbHd9MAXb8dwXBpHtSnC/XawsTg6m4GI4/rdMRIYRKtTMxOR9dB8fGIi6VFsfzfAEdZNkMCscsnt3p3n/4xll7KAWOoOLPJSYb7ukQSLVysVyy5fIch4hegEt9ac3HTHBERC5wxPtWUg8jkZbWLvN/BJfiDn+DeFtN6gqFz52emxQknVetSDMRadmQ8oBzwgBOVtLXJVaIjmy9HAzbmHr4K08vNsJV4pUVqk1MHd+tbHb1Lj2h8Raa/20hUq9FKABOFzC59j9r8qv/i/q+xLs7ndRdq2COH8hSqfYD/uNUBe8puknpMz27a2jDlhksk2PCXPhCieyODUqT3FJYATlXCx0QqgxWriDADwpNW8mZsy4Pyc96UMQ55CFVHjJcj6LvyGEj2cVdGXXuUN2zFlVGEDfrWBA3uzK8JApQLA=
